# Mojo  Basics

- Designed for high-performance systems programming
    - commonalities with C++ and Rust
- Superset of python

In [1]:
print("Hello world!")

Hello world!


## Language Basics

- Compiled language
    - either AOT or JIT
    - the `main` function serves as the entry point

In [7]:
fn main():
    var x: Int = 1
    x += 1 
    print(x)

- Can't run top-level code in .mojo files
- everything MUST be in a function or struct
- top level code only works in Notebooks and the REPL

## `fn` vs `def`

- `fn` enforces strongly-typed, memory-safe behavior
- `def` supports pythonic dynamic behavior

## variables

- declared with:
    - `var` for mutable values
    - `let` for immutable values

In [8]:
fn main():
    let x: Int = 1
    x += 1 
    print(x)

error: Expression [8]:3:5: expression must be mutable for in-place operator destination
    x += 1 
    ^

expression failed to parse (no further compiler diagnostics)

In [14]:
fn do_math():
    let x: Int = 1
    let y = 2
    print(x + y)

do_math()

3


**function args**

- types required for arguments and return variables
- arguments in a `fn` declaration are **Immutable** by default ("borrowing")
    - borrowing basically means that only the value of the variable is read
      but no copy is made.

In [13]:
fn add(x: Int, y: Int) -> Int:
    return x + y

z = add(1, 2)
print(z)

3


In [16]:
# optional args
fn pow(base: Int, exp: Int=2) -> Int:
    return base ** exp

# default
z = pow(2)
print(z)

# kwarg
z = pow(exp=3, base=2)
print(z)

4
8


In [19]:
fn add(borrowed x: Int, borrowed y: Int) -> Int:
    """Arguments are borrowed by default."""
    return x + y

print(add(1,2))

3


- to make the arguments mutable, use the `inout` keyword
    - changes mad inside the function are visible outside

In [20]:
fn add_inout(inout x: Int, inout y: Int) -> Int:
    x += 1
    return x+y

var a = 1
var b = 2
c = add_inout(a, b)

print(a)
print(b)
print(c)

2
2
4


- the `owned` argument will make the function the 'owner' of the value
    - it will be mutable, and also a unique copy

- mojo will make a copy of `a` and pass it to `text`.

In [21]:
fn set_fire(owned text: String) -> String:
    text += "🔥"
    return text

fn mojo():
    let a: String = "mojo"
    let b = set_fire(a)
    print(a)
    print(b)
mojo()

mojo
mojo🔥


- if copying is an expensive operation for the type of interest,
  ou can add the `^` transfer operator when passing args to a function
- this will transer ownership of the var to the function
    - destroy the local variable name

In [25]:
fn mojo():
    let a: String = "mojo"
    let b = set_fire(a^)
    print(a)
    print(b)

mojo()

error: Expression [25]:4:10: use of uninitialized value 'a'
    print(a)
         ^

Expression [25]:2:5: 'a' declared here
    let a: String = "mojo"
    ^

expression failed to parse (no further compiler diagnostics)

- as of 0.4.0, mojo always makes a copy when a function returns a value

### structures

- similar to python `class` -> supports methods, fields, operator overloading, decorators
- static types -> bound to compiile-time, do not allow runtime changes

In [27]:
struct MyPair:
    var first: Int
    var second: Int

    fn __init__(inout self, first: Int, second: Int):
        self.first = first
        self.second = second
    
    fn dump(self):
        print(self.first, self.second)

In [28]:
let mine = MyPair(2, 4)
mine.dump()

2 4


### python integration

- seamless integration with python modules

In [33]:
from python import Python

let np = Python.import_module("numpy")

ar = np.arange(15).reshape(3, 5)
print(ar)
print(ar.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
